### ISSUE TITLE
Implement contraction expansion for POS-tagger

### ISSUE THREAD

**Issue by tobybenjaminclark** [tambercore/hottnat#10]
Implement a function that takes a string containing contractions and returns the expanded form of those contractions. If a contraction has multiple possible expansions, only the first one will be returned. This will be called before lexicon initialisation in the brill tagger.

- There seems to be a dataset available [here](https://github.com/andrewbury/contractions)
- It should use the `&str` type

**Comment by aswarbs** [comment]
It seems that we didn't take capitalised words into account. Let's fix! :)

**Comment by tobybenjaminclark** [comment]
This has now been ammended.
